### PR TITLE
Add brute-force solution to guess protocol

### PR DESCRIPTION
**Pull request by TiberiumPY**
Some servers don't provide info about their version in 'Outdated Server' or 'Outdated client' and this is brute-force solution for it.

### CODE REVIEW

**Comment by TiberiumPY** [comment]
Wait, will fix now

**Comment by TiberiumPY** [comment]
OK, everything works now.. But I'm missing tests.. I dunno how to write test for this feature

**Comment by TiberiumPY** [comment]
No, nothing works :((

**Comment by joodicator** [comment]
This is a reasonable idea, since we know that there are servers with non-standard disconnect messages for version mismatches (see comments in issue #50 regarding ProtocolSupport, for example).

However, there are some problems with the way it was implemented in this pull request:

* A reconnection is attempted for **all** Disconnect packets received during the login state, including ones such as "Failed to verify username!", which can happen if a client tries to connect to an online-mode server without providing a valid authentication token. I can see two possible ways to get around this:

    1. Maintain a list of disconnect messages known to **not** indicate a version mismatch, and only attempt to reconnect for any other messages. This would require a careful analysis of the ways in which it is possible for a server to disconnect a client during login.

    2. Maintain a list of disconnect messages (or patterns that they satisfy) that the vanillla server and various third-party servers are known to send in the event of a version mismatch. This would probably require support to be added explicitly for each type of third party server.

    In my opinion the latter solution is likely to cause fewer problems, especially for cases where the current implementation already works.

* Attempting protocol versions in random order is probably not optimal, since it might cause the client to behave differently each time it connects, making problems harder to identify; and because it may result in the client choosing an older protocol version than the newest possible version, if the server supports multiple versions. If a brute-force search is to be attempted, it may be better to start from the highest version in `allowed_proto_versions` and continue in descending order.

Regarding the writing of tests for this implementation, I think some basic tests could be implemented by adapting the `FakeServer` class in `tests/test_connection.py` to behave like one or more third party servers. (I'm aware, however, that the test suite is not very good in general at the moment, and it would benefit from tests involving connecting to actual (updated) server instances - but that is a separate issue.)

However, there might be a way of solving this problem that doesn't require a brute-force approach, namely connecting to the server first in [Server List Ping](http://wiki.vg/Server_List_Ping) mode in order to retrieve the protocol version number (and the Minecraft version string, if needed). I am not sure if this interface is supported consistently by the third-party servers of interest, but if it is, this would make a more durable and portable solution to the protocol version negotiation problem.

In any case, @TiberiumPY or others interested in this issue, it would be useful to list some examples of third-party servers that you would like to use with pyCraft, so we can examine their behaviour before deciding how they can best be supported.

**Comment by TiberiumPY** [comment]
@joodicator SLP looks good, but we need to check if all servers supports with (e.g Spigot and Bukkit)

**Comment by joodicator** [comment]
In response to a server list ping,

* CraftBukkit replies with:  `'version': {'name': 'CraftBukkit 1.10.2', 'protocol': 210}`,

* Spigot replies with: `'version': {'name': 'Spigot 1.10.2', 'protocol': 210}`, and

* Spigot with ProtocolSupport replies with: `'version': {'name': 'Spigot 1.10.2', 'protocol': v}}`, where `v` appears to vary depending on the protocol version that the client supplies: it matches this version if the server supports it, or otherwise gives the server's highest supported version;

So it seems that the `protocol` field can generally be relied on, as long as the client provides its own highest supported version number when making the query.

For servers not supporting this interface, it could be made that `allowed_versions={v}` (that is, a singleton set containing just the version `v`) -- or `initial_version=v` when the server list ping attempt fails --  connects directly using that version without attempting a server list ping.

If somebody wishes to work on this, I would make the following recommendations:

* Remove in its entirety the existing code for automatic version negotiation, so we do not have to maintain two different systems solving the same problem, but:

* The API of pyCraft should remain backward compatible in terms of the accepted constructor arguments of `Connection`, and as much as possible in terms of behaviour, particularly for the parameters `initial_version` and `allowed_versions`.

Otherwise, I think I'll implement this change myself in the coming week.

**Comment by joodicator** [comment]
As of bf17f99083465a5d8968109d106deb0f9bb9256d, the above proposal has been implemented, and it should allow pyCraft to be used with Spigot and other non-standard servers.

**Pull request closed without merging**
