### PR TITLE
Support for v1.16.2

### PR DESCRIPTION
**Pull request by sillyfrog**
This builds on to of the work by starcraft66 in #168 . There has been a big change in the protocol since the snapshots (most clientbound values have reduced by 1). I have tested with the the current 1.16-pre2 and 1.16-rc1 server and client, and all appears to work, including most packets firing as expected. Unfortunately these changes were not yet up at https://wiki.vg/ when I started this work - so much of this was trial and error, figuring out what had changed since the last release.

It also includes a few things to assist in debugging, that does not change the core API.

Thanks!

### CODE REVIEW

**Comment by sillyfrog** [comment]
I have added support to 1.16.2 to this branch as well. This was a big change (again) of protocol numbers. There is still not correct support for the current world (now a variable length array). But it covers what I need, and figure it maybe of value to others.

**Comment by joodicator** [comment]
Thank you to everyone who contributed to this pull request. I have myself made some changes to bring the library up to date with 1.16.2. What remains is to bring the entity IDs for `SpawnObjectPacket` up to date.

I am prepared to merge this into `master` once it has undergone some additional testing.

**Comment by joodicator** [comment]
I accidentally merged this branch into `master`, when I meant to create a `v1.16` branch on `ammaraskar/pyCraft` so that it could be tested on Travis CI. Now I've reverted that, but it seems this pull request might remain marked as "merged".

**Comment by joodicator** [comment]
3c84c2a42986afbc13f049b1779816b358d28eeb merges these changes into `master`.

**Pull request merged**
